bynry_gas_company/bynry_gas_company/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("consumer_services.urls") )
]

bynry_gas_company/consumer_services/urls.py
from django.urls import include, path

from . import views


urlpatterns = [
    path("", views.consumer_home, name="consumer_home"),
    path("sign-up/", views.sign_up, name="consumer_sign_up"),
    path("login/", views.login, name="login"),
    path("requests/", views.myRequests, name="myRequests"),
    path("user_requests/", views.userRequests, name="userRequests"),
    path("customer_requests/", views.customerRequests, name="customerRequests"),
    path('create-service-request/', views.ServiceRequestView.as_view(), name='create_service_request'),
    path('service_requests/', views.ServiceRequestListView.as_view(), name='service_request_list'),
    path('service_requests/<int:pk>/', views.ServiceRequestDetailView.as_view(), name='service_request_detail'),
    path("logout/", views.logout, name="logout"),

]

bynry_gas_company/consumer_services/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
#from django.contrib.gis.db import models as gis_models
#from django.contrib.gis.geos import Point
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class BynryUserManager(BaseUserManager):
    def create_user(
        self,
        first_name,
        last_name,
        username,
        email,
        phone_number=None,
        password=None,
    ):
        if not email:
            raise ValueError("User must have an email address")

        if not username:
            raise ValueError("User must have an username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class BynryUser(AbstractBaseUser):
    MANAGER = 1
    CUSTOMER = 2
    test = 3

    ROLE_CHOICE = ((MANAGER, "manager"), (CUSTOMER, "Customer"))
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superadmin = models.BooleanField(default=False)

    # To set up customer default login field of the user use this property
    USERNAME_FIELD = "email"

    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    objects = BynryUserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def get_role(self):
        if self.role == 1:
            user_role = "Manager"
        else:
            user_role = "Customer"
        return user_role


class BynryUserProfile(models.Model):
    user = models.OneToOneField(
        BynryUser, on_delete=models.CASCADE, blank=True, null=True
    )
    profile_picture = models.ImageField(
        upload_to="users/profile_pictures", blank=True, null=True
    )
    cover_photo = models.ImageField(
        upload_to="users/cover_photos", blank=True, null=True
    )
    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    state = models.CharField(max_length=20, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    pin_code = models.CharField(max_length=6, blank=True, null=True)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)
    # spatial reference id default
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    # def full_address(self):
    #     return f"{self.address_line_1}, {self.address_line_2}"

    def __str__(self):
        return self.user.email

    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            #self.location = Point(float(self.longitude), float(self.latitude))
            pass
        return super(BynryUserProfile, self).save(*args, **kwargs)
    
class FileUpload(models.Model):
    file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


class ServiceRequests(models.Model):
    INSTALLATION = OPEN = LOW =0
    DELIVERY = ASSIGNED = MEDIUM =1
    SAFETY_INSPECTION = IN_PROGRESS = HIGH = 2
    MAINTENANCE = PENDING_CUSTOMER_RESPONSE = 3
    REPAIR = SCHEDULED = 4
    BILLING_ASSISTANCE = COMPLETED = 5
    ESCALATED = 6
    CLOSED = 7

    service_types = (
        (INSTALLATION, "Installation"),
        (DELIVERY, "Delivery"),
        (SAFETY_INSPECTION, "Safety Inspection"),
        (MAINTENANCE, "Maintenance"),
        (REPAIR, "Repairs"),
        (BILLING_ASSISTANCE, "Billing Assistance"),
    )

    status_types = (
        (OPEN, "Open"),
        (ASSIGNED, "Assigned"),
        (IN_PROGRESS, "In Progress"),
        (PENDING_CUSTOMER_RESPONSE, "Customer Response Pending"),
        (SCHEDULED, "Scheduled"),
        (COMPLETED, "Completed"),
        (ESCALATED, "Escalated"),
        (CLOSED, "Closed"),
    )
    PRIORITY_CHOICES = [
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    ]

    files = ArrayField(models.BigIntegerField(), null=True, blank=True)
    requested_by = models.ForeignKey(BynryUser, on_delete=models.CASCADE)
    service_type = models.PositiveSmallIntegerField(
        choices=service_types, blank=True, null=True
    )
    priority = models.PositiveSmallIntegerField(choices=PRIORITY_CHOICES, default=0)
    description = models.TextField()
    current_status = models.PositiveSmallIntegerField(
        choices=status_types, blank=True, null=True, default=0
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.requested_by

bynry_gas_company/consumer_services/views.py
from urllib import request
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.edit import FormView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin
from django.urls import reverse
from django.shortcuts import redirect
from .models import ServiceRequests
from .forms import ServiceRequestUpdateForm

from consumer_services.models import BynryUser
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import auth, messages

# Create your views here.
from .forms import BynryUserForm, ServiceRequestForm
from .models import FileUpload, ServiceRequests


def consumer_home(request):
    context = {}
    return render(request, "consumer_services/main.html", context)

def sign_up(request):
    if request.method == "POST":
        form = BynryUserForm(request.POST)
        if form.is_valid():
            # Create the user using form
            # user = form.save(commit=False)
            # password = form.cleaned_data["password"]
            # user.set_password(password)
            # user.role = User.CUSTOMER
            # user.save()

            # Create user using create_user method
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            username = form.cleaned_data["username"]
            phone_number = form.cleaned_data["phone_number"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = BynryUser.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=password,
                phone_number=phone_number,
            )
            user.role = BynryUser.CUSTOMER
            user.save()

            # Send verification email

            return redirect("consumer_sign_up")
        else:
            print("invalid form")
            print(form.errors)
            context = {"form": form}
            return render(request, "consumer_services/sign_up.html", context=context)

    else:
        form = BynryUserForm()
        context = {"form": form}
        return render(request, "consumer_services/sign_up.html", context)

def login(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already Logged in")
        return redirect("myRequests")

    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, "You are now logged in")
            print(messages)
            return redirect("myRequests")
        else:
            messages.error(request, "Invalid Login credentials")
            print(messages)
            return redirect("login")
    return render(request, "consumer_services/sign_in.html")
def detect_user(user):
    if user.role == 1:
        redirect_url = "customerRequests"
    elif user.role == 2:
        redirect_url = "userRequests"
    elif user.role == None and user.is_superadmin:
        redirect_url = "/admin"
    else:
        redirect_url = ""

    return redirect_url
@login_required(login_url="login")
def myRequests(request):
    user = request.user
    redirect_url = detect_user(user)
    return redirect(redirect_url)
    # context = {}
    # return render(request, "consumer_services/requests.html", context)

@login_required(login_url="login")
def customerRequests(request):
    user = request.user
    context = {}
    return render(request, "consumer_services/requests_cust.html", context)

@login_required(login_url="login")
def userRequests(request):
    user = request.user
    context = {}
    # return render(request, "consumer_services/requests_user.html", context)
    return redirect("create_service_request")


def logout(request):
    auth.logout(request)
    messages.info(request, "You are now logged out")
    return redirect("login")


# def create_service_request(request):
#     if request.method == 'POST':
#         form = ServiceRequestForm(request.POST, request.FILES)
#         if form.is_valid():
#             service_request = form.save()
#             return redirect('success_view')
#     else:
#         form = ServiceRequestForm()
#     return render(request, 'consumer_services/service_request_form.html', {'form': form})


class ServiceRequestView(LoginRequiredMixin,FormView):
    login_url = 'login'
    form_class = ServiceRequestForm
    template_name = 'consumer_services/service_request_form.html'  # Replace with your template.
    success_url = "/service_requests/"

    def form_valid(self, form):
            file_arr = []
            form.instance.requested_by = self.request.user 
            for each in form.cleaned_data['attachments']:
                pk_id = FileUpload.objects.create(file=each)
                file_arr.append(pk_id.pk)

            form.instance.files= file_arr

            form.save()
            return super(ServiceRequestView, self).form_valid(form)

class ServiceRequestListView(LoginRequiredMixin,ListView):
    login_url = 'login'
    model = ServiceRequests
    template_name = 'consumer_services/service_request_list.html'
    context_object_name = 'service_requests'  # This will be used in the template
    ordering = ['-created_at', 'updated_at']

    

    def get_queryset(self):
        print(self)
        if self.request.user.role != 1:
            return ServiceRequests.objects.filter(requested_by=self.request.user).order_by('-updated_at')
        else: 
            return ServiceRequests.objects.all().order_by('-updated_at')
    
def create_service_request(request):
    if request.method == 'POST':
         form = ServiceRequestForm(request.POST, request.FILES)
         files = request.FILES.getlist('files')
         if form.is_valid():
             for f in files:
                 file_instance = ServiceRequestForm(files=f)
                 file_instance.save()
    else:
         form = ServiceRequestForm()

    return render(request, "consumer_services/service_request_form.html", {'form': form})


class ServiceRequestDetailView(FormMixin, DetailView):
    model = ServiceRequests
    template_name = 'consumer_services/service_request_detail.html'
    form_class = ServiceRequestUpdateForm

    def get_success_url(self):
        return reverse('service_request_list', )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            # Update the current status and priority
            self.object.current_status = form.cleaned_data['current_status']
            self.object.priority = form.cleaned_data['priority']
            self.object.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

bynry_gas_company/templates/consumer_services/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Bynry Gas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.svg' %}">
</head>
<body>
    <div class="home">

        {% include "consumer_services/navbar.html" %} 
        <div class="container-fluid">
            {% block main_content %}
            {% include "consumer_services/main.html" %} 
            {% endblock main_content %}
        </div>
        

        {% include "consumer_services/footer.html" %} 
    </div>
    {% for message in messages %}
    <div class="modal fade" id="popupModal" tabindex="-1" aria-labelledby="popupModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="popupModalLabel">{{message}}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
        </div>
    </div>
</div>
{% endfor %}

</body>
<script>
    // Show the modal
    var myModal = new bootstrap.Modal(document.getElementById('popupModal'));
    myModal.show();
  
    // Auto-close after 3 seconds
    setTimeout(function() {
      myModal.hide();
    }, 3000);
  </script>
</html>

bynry_gas_company/templates/consumer_services/footer.html
<footer class="footer bg-dark">
    <div class="container">
      <span class="text-muted">    <p>
        © 2023 Bynry Gas Company. All Rights Reserved. Developed By
        <a href="https://www.sanketwagh.com">Sanket Wagh</a>
    </p></span>
    </div>
  </footer>

bynry_gas_company/templates/consumer_services/main.html
{% extends 'consumer_services/base.html' %}
{% block main_content %}
<div class="container py-3">
  <div class="px-4 py-4 my-5 text-center">
        <h1 class="display-5 fw-bold bynry">Bynry Gas </h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">Discover reliable and eco-friendly gas solutions with Bynry demo gas company. We offer residential, commercial, and industrial services, prioritizing safety, reliability, and environmental responsibility. Count on us for steady energy supply and top-notch customer support. Join us in shaping a cleaner, brighter future with natural gas.</p>
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <button type="button" class="btn btn-primary btn-lg px-4 gap-3"><a href="{% url 'consumer_sign_up' %}">Get connection</a></button>
            <button type="button" class="btn btn-outline-secondary btn-lg px-4"><a href="{% url 'consumer_sign_up' %}">Know more..</a></button>
          </div>
        </div>
      </div>
      
      
      <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Home</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$0<small class="text-muted fw-light">/mo extra</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>1 User</li>
                <li>One time installation Charges</li>
                <li>Email support</li>
                <li>Paid Call support</li>
                <li>7 day Service time</li>
              </ul>
              <a href="{% url 'consumer_sign_up' %}"><button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button></a>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Restaurants</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$15<small class="text-muted fw-light">/mo</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>Upto 5 User</li>
                <li>One time installation Charges</li>
                <li>Email support</li>
                <li>Free Call support</li>
                <li>2 day Service time</li>
              </ul>
              <a href="{% url 'consumer_sign_up' %}"><button type="button" class="w-100 btn btn-lg btn-primary">Get started</button></a>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm border-primary">
            <div class="card-header py-3 text-white bg-primary border-primary">
              <h4 class="my-0 fw-normal">Industrial</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$29<small class="text-muted fw-light">/mo</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>Upto 15 User</li>
                <li>One time installation Charges</li>
                <li>Email support</li>
                <li>Free Call support</li>
                <li>Same Day service</li>
              </ul>
              <a href="{% url 'consumer_sign_up' %}"><button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button></a>
            </div>
          </div>
        </div>
      </div>
      
      
      
    </main>
  
    
  </div>
  {% endblock main_content %}

bynry_gas_company/templates/consumer_services/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        <i class="bi bi-fire"></i>
        <span>Bynry Gas </span>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'consumer_sign_up' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Sign In</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Customer Services
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'myRequests' %}">New Service Request</a></li>
              <li><a class="dropdown-item" href="{% url 'service_request_list' %}">Status of request</a></li>
            </ul>
          </li>
          
        </ul>
        <ul>
          <li class="btn btn-primary logout"><a  href="{% url 'logout' %}">Logout</a></li>
        </ul>
        
      </div>
  </nav>

bynry_gas_company/templates/consumer_services/requests_cust.html
{% extends 'consumer_services/base.html' %}

{% block main_content %}
<h1>Customer Service Requests</h1>

<button class="btn btn-primary"><a href="{% url 'service_request_list' %}">View Customer Requests</a></button>
<button class="btn btn-primary"><a href="{% url 'create_service_request' %}">Requests new service</a></button>
{% endblock %}

bynry_gas_company/templates/consumer_services/requests_user.html
{% extends 'consumer_services/base.html' %} 
{% load static %}
{% block main_content %}
			
<div class="div">
    <button class="btn btn-primary"><a href="{% url 'service_request_list' %}">Existing</a></button>
    <button class="btn btn-primary"><a href="{% url 'create_service_request' %}">Requests new service</a></button>
</div>

{% endblock main_content %}

bynry_gas_company/templates/consumer_services/service_request_detail.html
{% extends 'consumer_services/base.html' %}

{% block main_content %}
  <div class="container">
    <h1 class="my-4">Service Request Detail</h1>
    <div class="card mb-4">
      <div class="card-body">
        <h2>Ticket ID: {{object.pk}}</h2>
        <h5 class="card-title">Requested by: {{ object.requested_by }}</h5>
        <p class="card-text">Service Type: {{ object.get_service_type_display }}</p>
        <!-- Add other fields as needed -->
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Update Status and Priority</h5>
        <form method="post" action="{% url 'service_request_detail' object.pk %}" enctype="multipart/form-data">
          {% csrf_token %}
          {% if request.user.role == 1 %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Update</button>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

bynry_gas_company/templates/consumer_services/service_request_form.html
{% extends 'consumer_services/base.html' %} 
{% load static %}
{% block main_content %}
<div class="container-service-request">
    <div></div>

    <div class="text-center mt-4">
        <h1>Create Service Request</h1>
        <form method="post" enctype="multipart/form-data" action="{% url 'create_service_request' %}">
            {% csrf_token %}
            <div class="">
                {% for field in form %}
                        <div>
                            {% if field.errors %}
                            <div class="control-group error">
                                <label class="control-label">{{ field.label }}</label>
                                <div class="controls">
                                    {{ field }}
                                    <span class="help-inline">
                                        {% for error in field.errors %}{{ error }}{% endfor %}
                                    </span>
                                </div>
                            </div>
                            {% else %}
                            <div class="control-group">
                                <label class="control-label">{{ field.label }}</label>
                                <div class="controls">
                                    {{ field }} {% if field.help_text %}
                                    <p class="help-inline">
                                        <small>{{ field.help_text }}</small>
                                    </p>
                                    {% endif %}
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary mt-4 register-btn">Submit</button>
                    </div>
            </div>
        </form>
    </div>
    <div></div>
</div>
{% endblock main_content %}

bynry_gas_company/templates/consumer_services/service_request_list.html
<!-- service_request_list.html -->
{% extends 'consumer_services/base.html' %}

{% block main_content %}
<h1>Service Requests</h1>
<ul class="service_request_list" >
    {% for service_request in service_requests %}
      <li>
        <div class="card ticket-card {% if service_request.get_current_status_display|lower == 'closed' %}closed {% endif %}" style="width: 18rem;">
            <div class="card-body">
              <h2>Ticket ID: {{service_request.pk}}</h2>
              {% if request.user.role == 1 %}
              <h5 class="card-title"> {{service_request.requested_by}}  </h5>
                {% endif %}
              <h5 class="card-title">{{ service_request.get_service_type_display }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ service_request.get_current_status_display }}</h6>
              <h6 class="card-subtitle mb-2 text-muted">Created at: {{ service_request.created_at }}</h6>
              <h6 class="card-subtitle mb-2 text-muted">Last Updated: {{ service_request.updated_at }}</h6>
              <p class="card-text {{service_request.get_priority_display|lower}}">Priority: {{ service_request.get_priority_display }}</p>
              <p class="card-text">    {{service_request.description}}</p>
              {% if request.user.role == 1 %}
              <button class="btn btn-primary" type="button"><a href="{% url 'service_request_detail' pk=service_request.pk %}" class="card-link">Update ticket</a></button>
              {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
<button class="btn btn-primary"><a href="{% url 'create_service_request' %}">Requests new service</a></button>
{% endblock %}

bynry_gas_company/templates/consumer_services/sign_in.html
{% extends 'consumer_services/base.html' %} 
{% load static %}
{% block main_content %}
	
    {% csrf_token %}
    <div class="login-page text-center">
        <div></div>

        <form class="form-logo" method="post"
        action="{% url 'login' %}"
        enctype="multipart/form-data">
        {% csrf_token %}
            <i class="bi bi-fire" ></i>
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
            
            <div class="form-floating">
                <input type="email" class="form-control" id="floatingInput" name="email" placeholder="name@example.com">
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
          <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password">
          <label for="floatingPassword">Password</label>
        </div>
    
        
        <button class="w-100 btn btn-lg btn-primary mt-4" type="submit">Sign in</button>
        <a href="{% url 'consumer_sign_up' %}"><button type="button" class="w-100 btn btn-lg btn-primary mt-4" >Register</button></a>
        <p class="mt-5 mb-3 text-muted">© Bynry</p>
    </form>
    {{request.user.role}}
</div>
{% endblock main_content %}